### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Laravel doesn't follow semver. So having `^5.x`, `5.*` or `>=5.x` will mean that composer will install a future version even though that version breaks the package.

### CODE REVIEW

**Comment by dwightwatson** [comment]
Is this an automated PR or something?

**Comment by Dylan-DPC** [comment]
@dwightwatson No it is not. I do it manually and use an auto-reply for the message here. (in case you saw it elsewhere)

**Comment by dwightwatson** [comment]
Oh okay, was just wondering as this repo is still a work in progress without any users so was curious as to how it was found. Thanks for the change though, makes sense.

**Comment by Dylan-DPC** [comment]
All laravel repos that recently updated can be found [here](https://github.com/topics/laravel?o=desc&s=updated). I often check that list.

**Comment by dwightwatson** [comment]
Oh cool, never seen that before. Thanks for letting me know!

**Pull request merged**
